version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=trading_platform'

  app:
    build: ./
    container_name: 'trading-platform'
    ports:
      - "8080:8080"